apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          {{- if .Values.rbac.create }}
          serviceAccountName: {{ .Release.Name }}
          {{- end }}
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
          containers:
            - name: helm-scraper
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: "{{ .Values.image.pullPolicy }}"
              {{- if .Values.env }}
              env:
              {{- range $name, $value := .Values.env }}
                - name: {{ $name }}
                  value: {{ $value }}
              {{- end }}
              {{- end }}
