apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scraper-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: default
roleRef:
  kind: ClusterRole
  name: scraper-role
  apiGroup: rbac.authorization.k8s.io