apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scraper-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: default
roleRef:
  kind: Role
  name: scraper-role
  apiGroup: rbac.authorization.k8s.io